# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8406c7220a53356a098da38fb117df393b85aa60583ec7495dd9b5664b8e56a7b78dfea74d320a8dc638d5043f2748ac795ecbf5cf702a8f56ad1bfd91a695c2

test:
  secret_key_base: 98f387c594ac30fa3565697188408aa7d78ed6c18699cf6b39072785575cf9a8e0f5737a3ac4f415e75bd4236c2f165f706715c2d70a363d26339298a5e2e7d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
